import { useEffect, useState } from "react";
import { X } from "lucide-react";
import { listExtensions, saveExtension, setExtensionEnabled, validateExtensionManifest, type DevTerminalExtension } from "@/lib/extension-registry";
import { Button } from "@/components/ui/button";
import { Label } from "@/components/ui/label";
import { Slider } from "@/components/ui/slider";
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs";
import { useIDE } from "@/contexts/IDEContext";

export function SettingsPanel({ onClose }: { onClose: () => void }) {
  const { preferences, updatePreferences } = useIDE();
  const [extensions, setExtensions] = useState<DevTerminalExtension[]>([]);
  useEffect(() => setExtensions(listExtensions()), []);
  const importExtension = async (file: File) => {
    try {
      const manifest = validateExtensionManifest(JSON.parse(await file.text()));
      setExtensions(saveExtension(manifest));
    } catch (error) {
      alert(error instanceof Error ? error.message : "Manifesto inválido.");
    }
  };
  return (
    <div className="fixed inset-0 z-50 grid place-items-center bg-black/60 p-4 backdrop-blur-sm" onClick={onClose}>
      <div className="w-full max-w-2xl overflow-hidden rounded-xl border border-white/[0.1] bg-[#15161c] shadow-2xl" onClick={(event) => event.stopPropagation()}>
        <div className="flex items-center justify-between border-b border-white/[0.07] px-5 py-4"><div><p className="text-xs font-semibold uppercase tracking-[0.16em] text-zinc-500">Personalização</p><h2 className="mt-1 text-lg font-semibold text-zinc-100">Configurações da IDE</h2></div><Button variant="ghost" size="icon" className="h-8 w-8 text-zinc-500 hover:bg-white/[0.08] hover:text-zinc-200" onClick={onClose}><X size={16} /></Button></div>
        <Tabs defaultValue="editor" className="flex min-h-[390px]">
          <TabsList className="h-auto w-40 shrink-0 flex-col items-stretch justify-start gap-1 rounded-none border-r border-white/[0.07] bg-[#111217] p-3"><TabsTrigger value="editor" className="justify-start text-xs">Editor</TabsTrigger><TabsTrigger value="terminal" className="justify-start text-xs">Terminal</TabsTrigger><TabsTrigger value="shortcuts" className="justify-start text-xs">Atalhos</TabsTrigger><TabsTrigger value="extensions" className="justify-start text-xs">Extensões</TabsTrigger></TabsList>
          <div className="min-w-0 flex-1 p-6">
            <TabsContent value="editor" className="mt-0 space-y-6"><div><p className="text-sm font-medium text-zinc-200">Editor</p><p className="mt-1 text-xs text-zinc-600">Ajuste a leitura e a navegação do código.</p></div><div className="space-y-3"><Label className="text-xs text-zinc-400">Tamanho da fonte <span className="text-zinc-600">{preferences.editorFontSize}px</span></Label><Slider value={[preferences.editorFontSize]} min={10} max={22} step={1} onValueChange={(value) => updatePreferences({ editorFontSize: value[0] })} /></div><div className="grid grid-cols-2 gap-4"><div className="space-y-2"><Label className="text-xs text-zinc-400">Tab size</Label><select className="h-9 w-full rounded-md border border-white/[0.1] bg-[#101116] px-3 text-xs text-zinc-300" value={preferences.tabSize} onChange={(event) => updatePreferences({ tabSize: Number(event.target.value) })}><option value={2}>2 espaços</option><option value={4}>4 espaços</option><option value={8}>8 espaços</option></select></div><div className="space-y-2"><Label className="text-xs text-zinc-400">Quebra de linha</Label><select className="h-9 w-full rounded-md border border-white/[0.1] bg-[#101116] px-3 text-xs text-zinc-300" value={preferences.wordWrap} onChange={(event) => updatePreferences({ wordWrap: event.target.value as "on" | "off" })}><option value="on">Ativada</option><option value="off">Desativada</option></select></div></div><label className="flex items-center justify-between rounded-lg border border-white/[0.08] bg-white/[0.02] px-3 py-3 text-xs text-zinc-400"><span>Minimap do editor</span><input type="checkbox" checked={preferences.minimap} onChange={(event) => updatePreferences({ minimap: event.target.checked })} /></label></TabsContent>
            <TabsContent value="terminal" className="mt-0 space-y-6"><div><p className="text-sm font-medium text-zinc-200">Terminal</p><p className="mt-1 text-xs text-zinc-600">Defina a aparência do shell e reduza o ruído visual.</p></div><div className="space-y-3"><Label className="text-xs text-zinc-400">Tamanho da fonte <span className="text-zinc-600">{preferences.terminalFontSize}px</span></Label><Slider value={[preferences.terminalFontSize]} min={10} max={20} step={1} onValueChange={(value) => updatePreferences({ terminalFontSize: value[0] })} /></div><div className="space-y-2"><Label className="text-xs text-zinc-400">Esquema de cores</Label><select className="h-9 w-full rounded-md border border-white/[0.1] bg-[#101116] px-3 text-xs text-zinc-300" value={preferences.terminalTheme} onChange={(event) => updatePreferences({ terminalTheme: event.target.value as "midnight" | "solarized" | "mono" })}><option value="midnight">Midnight blue</option><option value="solarized">Solarized dark</option><option value="mono">Monochrome</option></select></div><div className="space-y-2"><Label className="text-xs text-zinc-400">Família tipográfica</Label><input className="h-9 w-full rounded-md border border-white/[0.1] bg-[#101116] px-3 text-xs text-zinc-300 outline-none focus:border-blue-400" value={preferences.terminalFontFamily} onChange={(event) => updatePreferences({ terminalFontFamily: event.target.value })} /></div></TabsContent>
            <TabsContent value="shortcuts" className="mt-0 space-y-3"><div><p className="text-sm font-medium text-zinc-200">Atalhos essenciais</p><p className="mt-1 text-xs text-zinc-600">Ações rápidas para manter o foco no teclado.</p></div>{[["Salvar sessão", "⌘ / Ctrl + S"], ["Abrir configurações", "⌘ / Ctrl + ,"], ["Alternar Explorer", "⌘ / Ctrl + B"], ["Focar terminal", "⌘ / Ctrl + `"], ["Novo arquivo", "⌘ / Ctrl + N"]].map(([label, shortcut]) => <div key={label} className="flex items-center justify-between rounded-lg border border-white/[0.07] px-3 py-2.5 text-xs"><span className="text-zinc-400">{label}</span><kbd className="rounded bg-white/[0.07] px-2 py-1 font-mono text-[10px] text-zinc-300">{shortcut}</kbd></div>)}</TabsContent>
            <TabsContent value="extensions" className="mt-0 space-y-4"><div><p className="text-sm font-medium text-zinc-200">Extensibilidade</p><p className="mt-1 text-xs leading-5 text-zinc-600">Importe manifestos JSON locais. As permissões são exibidas antes de ativar cada extensão.</p></div><label className="flex cursor-pointer items-center justify-center rounded-lg border border-dashed border-white/[0.12] bg-white/[0.02] p-4 text-xs text-zinc-400 hover:border-blue-400/40 hover:text-zinc-200">Importar manifesto JSON<input type="file" accept="application/json,.json" className="hidden" onChange={(event) => { const file = event.target.files?.[0]; if (file) void importExtension(file); event.target.value = ""; }} /></label><div className="space-y-2">{extensions.length === 0 ? <p className="py-3 text-xs text-zinc-600">Nenhuma extensão instalada.</p> : extensions.map((extension) => <div key={extension.id} className="rounded-lg border border-white/[0.08] bg-white/[0.02] p-3"><div className="flex items-center justify-between"><div><p className="text-xs font-medium text-zinc-200">{extension.name} <span className="text-zinc-600">v{extension.version}</span></p><p className="mt-1 text-[10px] text-zinc-600">{extension.description || extension.id}</p></div><input type="checkbox" checked={extension.enabled} onChange={(event) => setExtensions(setExtensionEnabled(extension.id, event.target.checked))} /></div><div className="mt-2 flex flex-wrap gap-1">{extension.permissions.map((permission) => <span key={permission} className="rounded bg-white/[0.06] px-1.5 py-0.5 text-[9px] text-zinc-500">{permission}</span>)}</div></div>)}</div></TabsContent>
          </div>
        </Tabs>
        <div className="flex justify-end border-t border-white/[0.07] px-5 py-3"><Button className="h-8 bg-blue-600 text-xs hover:bg-blue-500" onClick={onClose}>Concluir</Button></div>
      </div>
    </div>
  );
}
